services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omnibioai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  workbench:
    image: ghcr.io/man4ish/omnibioai:latest
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis

  tes:
    image: ghcr.io/man4ish/omnibioai-tes:latest
    ports:
      - "8081:8081"
    environment:
      TOOLSERVER_URL: http://toolserver:9090
    depends_on:
      - toolserver
      - redis
      - mysql

  toolserver:
    image: ghcr.io/man4ish/omnibioai-toolserver:latest
    ports:
      - "9090:9090"
    depends_on:
      - mysql

  model-registry:
    image: ghcr.io/man4ish/omnibioai-model-registry:latest
    ports:
      - "8095:8095"
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql

  lims:
    image: ghcr.io/man4ish/omnibioai-lims-x:latest
    ports:
      - "7000:7000"
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql

  control-center:
    image: ghcr.io/man4ish/omnibioai-control-center:latest
    ports:
      - "7070:7070"
    depends_on:
      - workbench
      - tes
      - toolserver

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command: ["run", "--server"]

volumes:
  mysql_data:
  redis_data:
