#!/bin/bash
# OmniBioAI Studio — portable start script
# Works standalone (outside Electron) by reading the .env generated by the app.
set -euo pipefail

echo "======================================"
echo " OmniBioAI Studio Startup"
echo "======================================"

# ─── Locate compose file ──────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Prefer release compose (ghcr.io images) if available
if [ -f "$SCRIPT_DIR/../docker-compose.release.yml" ]; then
  COMPOSE_FILE="$SCRIPT_DIR/../docker-compose.release.yml"
  echo "[OK] Using release compose: $COMPOSE_FILE"
elif [ -f "$SCRIPT_DIR/../docker-compose.yml" ]; then
  COMPOSE_FILE="$SCRIPT_DIR/../docker-compose.yml"
  echo "[OK] Using compose: $COMPOSE_FILE"
else
  echo "[ERROR] No compose file found in $SCRIPT_DIR/.."
  exit 1
fi

# ─── Login to ghcr.io if token available ──────────────
if [ -n "${GHCR_TOKEN:-}" ]; then
  echo "Logging into ghcr.io..."
  echo "$GHCR_TOKEN" | docker login ghcr.io -u man4ish --password-stdin \
    && echo "[OK] ghcr.io login successful" \
    || echo "[WARN] ghcr.io login failed — private images may not pull"
else
  echo "[WARN] No GHCR_TOKEN set — private images may fail to pull"
fi

# ─── Find .env generated by the Electron app ─────────
ENV_FILE=""
for candidate in \
  "$HOME/.config/OmniBioAI-Studio/.env" \
  "$HOME/Library/Application Support/OmniBioAI-Studio/.env" \
  "$SCRIPT_DIR/../.env"
do
  if [ -f "$candidate" ]; then
    ENV_FILE="$candidate"
    break
  fi
done

if [ -n "$ENV_FILE" ]; then
  echo "[OK] Loading environment from $ENV_FILE"
  set -a
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  set +a
else
  echo "[WARN] No .env found — using defaults (run the Studio app first to generate it)"
  export DATA_DIR="${DATA_DIR:-$HOME/omnibioai/data}"
  export WORK_DIR="${WORK_DIR:-$HOME/omnibioai/work}"
  export WORKSPACE_HOST="${WORKSPACE_HOST:-$HOME/omnibioai/work}"
  export DB_INIT_DIR="$SCRIPT_DIR/../db-init"
  export VIDEO_DIR="$WORK_DIR/videos"
  export MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-omnibioai}"
  export MYSQL_DEFAULT_DB="${MYSQL_DEFAULT_DB:-omnibioai}"
  export HOST_IP="0.0.0.0"
fi

echo "Mode:       ${MODE:-local}"
echo "Data Dir:   $DATA_DIR"
echo "Work Dir:   $WORK_DIR"
echo "Workspace:  $WORKSPACE_HOST"

# ─── Create workspace directories ─────────────────────
mkdir -p "$DATA_DIR/PubMed/Abstracts"
mkdir -p "$DATA_DIR/PubMed/Index"
mkdir -p "$DATA_DIR/model_registry"
mkdir -p "$DATA_DIR/tool-images/dockerfiles"
mkdir -p "$DATA_DIR/tool-images/sif"
mkdir -p "$WORK_DIR/uploads"
mkdir -p "$WORK_DIR/runs"
mkdir -p "$WORK_DIR/videos"

# ─── Stop conflicting host services ───────────────────
for svc in mysql redis-server; do
  if systemctl is-active --quiet "$svc" 2>/dev/null; then
    echo "[WARN] Stopping host $svc to free ports..."
    sudo systemctl stop "$svc" 2>/dev/null || true
  fi
done

# ─── Build compose args ───────────────────────────────
COMPOSE_ARGS="-f $COMPOSE_FILE"
[ -n "$ENV_FILE" ] && COMPOSE_ARGS="$COMPOSE_ARGS --env-file $ENV_FILE"

# ─── Pull images ──────────────────────────────────────
echo ""
echo "Pulling latest images (this may take a while)..."
docker compose $COMPOSE_ARGS pull || echo "[WARN] Some images could not be pulled, using cached versions"

# ─── Download SIF images ──────────────────────────────
SIF_DIR="${DATA_DIR}/tool-images/sif"
mkdir -p "$SIF_DIR"

if [ "${SKIP_SIF:-0}" = "1" ]; then
  echo ""
  echo "[SKIP] SIF image download skipped (SKIP_SIF=1)"
else
  echo ""
  echo "Downloading SIF images (this may take 30-60 minutes on first run)..."
  echo "Core bioinformatics tools: ~20GB"
  echo "You can skip with: SKIP_SIF=1 bash scripts/start.sh"

  # Core tools needed for workflows
  CORE_TOOLS="fastqc multiqc trimmomatic samtools bwa star
              gatk deseq2 salmon kallisto hisat2 bcftools
              bismark kraken2 scanpy seurat pytorch tensorflow"

  for tool in $CORE_TOOLS; do
    SIF_PATH="$SIF_DIR/${tool}_arm64.sif"
    if [ ! -f "$SIF_PATH" ]; then
      echo "  Downloading ${tool}..."
      singularity pull "$SIF_PATH" \
        oras://ghcr.io/man4ish/omnibioai-sif/${tool}:arm64 \
        2>/dev/null || echo "  [WARN] Could not download ${tool}"
    else
      echo "  [OK] ${tool} already present"
    fi
  done

  echo "SIF images ready at: $SIF_DIR"
fi

# ─── Start services ───────────────────────────────────
echo ""
echo "Starting services..."
docker compose $COMPOSE_ARGS up -d

# ─── Wait for workbench ───────────────────────────────
echo ""
echo "Waiting for workbench to be ready..."
READY=0
for i in $(seq 1 30); do
  if curl -sf http://localhost:8000/health/ >/dev/null 2>&1; then
    READY=1
    break
  fi
  printf "  ... %d/30\r" "$i"
  sleep 5
done

echo ""
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
echo ""

if [ "$READY" -eq 1 ]; then
  echo "======================================"
  echo " OmniBioAI Studio is ready"
  echo " Workbench:      http://localhost:8000"
  echo " TES:            http://localhost:8081"
  echo " Ollama:         http://localhost:11434"
  echo " Control Center: http://localhost:7070"
  echo " LIMS:           http://localhost:7000"
  echo "======================================"
else
  echo "[WARN] Workbench did not respond in time — check logs with: docker compose logs workbench"
fi
