#!/bin/bash
# OmniBioAI Studio — portable start script
# Works standalone (outside Electron) by reading the .env generated by the app.
set -euo pipefail

echo "======================================"
echo " OmniBioAI Studio Startup"
echo "======================================"

# ─── Locate compose file ──────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/../docker-compose.yml"

if [ ! -f "$COMPOSE_FILE" ]; then
  echo "[ERROR] docker-compose.yml not found at $COMPOSE_FILE"
  exit 1
fi

# ─── Find .env generated by the Electron app ─────────
ENV_FILE=""
for candidate in \
  "$HOME/.config/OmniBioAI-Studio/.env" \
  "$HOME/Library/Application Support/OmniBioAI-Studio/.env" \
  "$SCRIPT_DIR/../.env"
do
  if [ -f "$candidate" ]; then
    ENV_FILE="$candidate"
    break
  fi
done

if [ -n "$ENV_FILE" ]; then
  echo "[OK] Loading environment from $ENV_FILE"
  set -a
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  set +a
else
  echo "[WARN] No .env found — using defaults (run the Studio app first to generate it)"
  export DATA_DIR="${DATA_DIR:-$HOME/omnibioai/data}"
  export WORK_DIR="${WORK_DIR:-$HOME/omnibioai/work}"
  export WORKSPACE_HOST="${WORKSPACE_HOST:-$HOME/omnibioai/work}"
  export DB_INIT_DIR="$SCRIPT_DIR/../db-init"
  export VIDEO_DIR="$WORK_DIR/videos"
  export MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-omnibioai}"
  export MYSQL_DEFAULT_DB="${MYSQL_DEFAULT_DB:-omnibioai}"
  export HOST_IP="0.0.0.0"
fi

echo "Mode:       ${MODE:-local}"
echo "Data Dir:   $DATA_DIR"
echo "Work Dir:   $WORK_DIR"
echo "Workspace:  $WORKSPACE_HOST"

# ─── Create workspace directories ─────────────────────
mkdir -p "$DATA_DIR/PubMed/Abstracts"
mkdir -p "$DATA_DIR/PubMed/Index"
mkdir -p "$DATA_DIR/model_registry"
mkdir -p "$DATA_DIR/tool-images/dockerfiles"
mkdir -p "$DATA_DIR/tool-images/sif"
mkdir -p "$WORK_DIR/uploads"
mkdir -p "$WORK_DIR/runs"
mkdir -p "$WORK_DIR/videos"

# ─── Stop conflicting host services ───────────────────
for svc in mysql redis-server; do
  if systemctl is-active --quiet "$svc" 2>/dev/null; then
    echo "[WARN] Stopping host $svc to free ports..."
    sudo systemctl stop "$svc" 2>/dev/null || true
  fi
done

# ─── Build compose args ───────────────────────────────
COMPOSE_ARGS="-f $COMPOSE_FILE"
[ -n "$ENV_FILE" ] && COMPOSE_ARGS="$COMPOSE_ARGS --env-file $ENV_FILE"

# ─── Pull images ──────────────────────────────────────
echo ""
echo "Pulling latest images (this may take a while)..."
docker compose $COMPOSE_ARGS pull || echo "[WARN] Some images could not be pulled, using cached versions"

# ─── Start services ───────────────────────────────────
echo ""
echo "Starting services..."
docker compose $COMPOSE_ARGS up -d

# ─── Wait for workbench ───────────────────────────────
echo ""
echo "Waiting for workbench to be ready..."
READY=0
for i in $(seq 1 30); do
  if curl -sf http://localhost:8000/health/ >/dev/null 2>&1; then
    READY=1
    break
  fi
  printf "  ... %d/30\r" "$i"
  sleep 5
done

echo ""
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
echo ""

if [ "$READY" -eq 1 ]; then
  echo "======================================"
  echo " OmniBioAI Studio is ready"
  echo " Workbench:      http://localhost:8000"
  echo " TES:            http://localhost:8081"
  echo " Ollama:         http://localhost:11434"
  echo " Control Center: http://localhost:7070"
  echo " LIMS:           http://localhost:7000"
  echo "======================================"
else
  echo "[WARN] Workbench did not respond in time — check logs with: docker compose logs workbench"
fi
